# Generated by Django 5.1.15 on 2026-09-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=160)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('max_amount', models.BigIntegerField()),
                ('term_months', models.PositiveIntegerField(default=24)),
                ('grace_months', models.PositiveIntegerField(default=0)),
                ('collateral', models.CharField(blank=True, max_length=160)),
                ('guarantee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subsidy_rule', models.JSONField(blank=True, default=dict)),
                ('eligibility', models.JSONField(blank=True, default=dict)),
                ('legal_ref_url', models.URLField(blank=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('base', models.CharField(default='turnover', max_length=32)),
                ('threshold_min', models.BigIntegerField(default=0)),
                ('threshold_max', models.BigIntegerField(blank=True, null=True)),
                ('sector_filter', models.JSONField(blank=True, default=list)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('legal_ref_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('inputs', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('price_snapshot', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='ledger.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(blank=True, max_length=512)),
                ('summary', models.JSONField(default=dict)),
                ('consent', models.BooleanField(default=False)),
                ('sent_to_bank_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='ledger.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.businessplan')),
            ],
        ),
        migrations.CreateModel(
            name='CreditReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('factors', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kti', to='ledger.business')),
            ],
        ),
        migrations.CreateModel(
            name='StressTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField(default=1000)),
                ('p_loss', models.FloatField()),
                ('p10', models.BigIntegerField()),
                ('p50', models.BigIntegerField()),
                ('p90', models.BigIntegerField()),
                ('top_risk_factor', models.CharField(max_length=64)),
                ('histogram', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_runs', to='finance.businessplan')),
            ],
        ),
    ]
