# Generated by Django 5.1.15 on 2026-09-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=128)),
                ('name_ru', models.CharField(blank=True, max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=128)),
                ('name_ru', models.CharField(blank=True, max_length=128)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('base_unit', models.CharField(default='kg', max_length=16)),
                ('is_social', models.BooleanField(default=False)),
                ('typical_pack_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('typical_pack_unit', models.CharField(default='kg', max_length=16)),
                ('demo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name_uz'],
            },
        ),
    ]
