# Generated by Django 5.1.15 on 2026-09-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sector', models.CharField(default='ovqatlanish', max_length=64)),
                ('legal_status', models.CharField(choices=[('informal', 'Norasmiy'), ('self_employed', "O'zini o'zi band"), ('yatt', 'YaTT'), ('llc', 'MChJ')], default='informal', max_length=24)),
                ('tax_regime', models.CharField(blank=True, max_length=32)),
                ('monthly_revenue', models.BigIntegerField(default=0)),
                ('employees', models.PositiveIntegerField(default=2)),
                ('is_demo', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='markets.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=16)),
                ('amount', models.BigIntegerField()),
                ('category', models.CharField(blank=True, max_length=64)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('source', models.CharField(choices=[('voice', 'Ovoz'), ('text', 'Matn'), ('manual', "Qo'lda")], default='manual', max_length=16)),
                ('raw_text', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
