# Generated by Django 5.1.15 on 2026-09-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='markets.district'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='business',
            name='sector',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
