# Generated by Django 5.1.15 on 2026-09-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=128)),
                ('name_ru', models.CharField(blank=True, max_length=128)),
                ('is_city', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=128)),
                ('name_ru', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=160)),
                ('name_ru', models.CharField(blank=True, max_length=160)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type', models.CharField(choices=[('dehqon', 'Dehqon bozori'), ('ulgurji', 'Ulgurji'), ('supermarket', 'Supermarket'), ('onlayn', 'Onlayn')], default='dehqon', max_length=24)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='markets.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='markets.region'),
        ),
    ]
