# Generated by Django 5.1.15 on 2026-09-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Ayol'), ('male', 'Erkak')], max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='markets.market'),
        ),
        migrations.AddField(
            model_name='user',
            name='stir',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Xaridor'), ('entrepreneur', 'Tadbirkor'), ('supplier', 'Yetkazib beruvchi'), ('market_admin', "Bozor ma'muri"), ('bank', 'Bank'), ('admin', 'Admin')], default='entrepreneur', max_length=32),
        ),
    ]
