# Generated by Django 5.1.15 on 2026-09-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('yahoo_symbol', models.CharField(blank=True, max_length=32)),
                ('base_uzs', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(default="O'zbekiston", max_length=64)),
                ('market_name', models.CharField(default="Milliy o'rtacha", max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.BigIntegerField()),
                ('high', models.BigIntegerField()),
                ('low', models.BigIntegerField()),
                ('close', models.BigIntegerField()),
                ('source', models.CharField(default='yahoo', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market.marketinstrument')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['instrument', 'date'], name='market_cand_instrum_afe58e_idx')],
                'unique_together': {('instrument', 'date')},
            },
        ),
    ]
