# Generated by Django 5.1.15 on 2026-09-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='lt', max_length=16)),
                ('threshold', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.PositiveIntegerField(default=7)),
                ('yhat', models.JSONField(default=list)),
                ('lo', models.JSONField(default=list)),
                ('hi', models.JSONField(default=list)),
                ('signal', models.CharField(choices=[('HOZIR OL', 'HOZIR OL'), ('KUT', 'KUT'), ('NEYTRAL', 'NEYTRAL')], default='NEYTRAL', max_length=16)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('model_version', models.CharField(default='ets-v0', max_length=32)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='markets.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'market', 'horizon')},
            },
        ),
        migrations.CreateModel(
            name='PriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.BigIntegerField()),
                ('high', models.BigIntegerField()),
                ('low', models.BigIntegerField()),
                ('close', models.BigIntegerField()),
                ('median', models.BigIntegerField()),
                ('n_obs', models.PositiveIntegerField(default=1)),
                ('is_demo', models.BooleanField(default=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='markets.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='catalog.product')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['product', 'market', 'date'], name='prices_pric_product_f62de8_idx')],
                'unique_together': {('product', 'market', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_base_unit', models.BigIntegerField()),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('raw_text', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('crowd', 'Crowd'), ('scrape', 'Scrape'), ('stat', 'Statistika'), ('uzex', 'UzEx'), ('partner', 'Hamkor'), ('demo', 'DEMO')], default='crowd', max_length=16)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.8, max_digits=4)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('review', 'Tekshiruvda'), ('rejected', 'Rad etilgan')], default='ok', max_length=16)),
                ('media_url', models.CharField(blank=True, max_length=512)),
                ('anomaly_z', models.FloatField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.JSONField(blank=True, default=dict)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='markets.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_obs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['product', 'market', 'observed_at'], name='prices_pric_product_5daa23_idx'), models.Index(fields=['status', 'observed_at'], name='prices_pric_status_b3696d_idx')],
            },
        ),
    ]
